---
title: "Real dataset"
author: "Kalidou BA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test_simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
# library(DICEPRO)
devtools::load_all()
library(ADAPTS)
library(NMF)
library(MASS)
library(jsonlite)
library(dplyr)
```


```{r metri function}
compute_metrics <- function(true, pred) {
  true_normalized <- t(apply(true, 1, function(x) x / sum(x)))
  pred_normalized <- t(apply(pred, 1, function(x) x / sum(x)))
  r2_value <- cor(as.vector(true_normalized), as.vector(pred_normalized))^2
  rmse_value <- rmse(true_normalized, pred_normalized)
  
  rrmse_value <- rmse_value / mean(true_normalized)
  result <- list(
    R2 = r2_value,
    RMSE = rmse_value,
    RRMSE = rrmse_value
  )
  return(result)
}
```


```{r load_data bulk}
mixDatasetName <- "CellMixtures"
file_path <- system.file("extdata", "mixing", paste0(mixDatasetName,".rda"), package = "DICEPRO")
tmp_env <- new.env()
load(file_path, envir = tmp_env)
loaded_names <- ls(tmp_env)
mixDataset <- tmp_env[[loaded_names[1]]]
rownames(mixDataset) <- mixDataset[,1]
mixDataset <- mixDataset[,-1]
head(mixDataset)
```


```{r load_data refernces}
refDatasetName <- "10XImmune"
file_path <- system.file("extdata", "references", paste0(refDatasetName,".rda"), package = "DICEPRO")
tmp_env <- new.env()
load(file_path, envir = tmp_env)
loaded_names <- ls(tmp_env)
refDataset <- tmp_env[[loaded_names[1]]]
rownames(refDataset) <- refDataset[,1]
refDataset <- refDataset[,-1]
head(refDataset)
```


<!-- ```{r run DICEPRO} -->
<!-- DICEPRO::DICEPRO(reference = refDataset, bulk = mixDataset, methodDeconv = "DCQ", refName = "10XImmune", bulkName = "CellMixtures", hp_max_evals = 5) -->
<!-- ``` -->


<!-- ```{r execute with best HyperParams} -->
<!-- P_cb <- t(DICEPRO::running_method(reference = refDataset, bulk = mixDataset, methodDeconv = "DCQ")) -->

<!-- geneIntersect <- intersect(rownames(refDataset), rownames(mixDataset)) -->

<!-- refDataset <- apply(refDataset[geneIntersect, ], 2, as.numeric) -->
<!-- mixDataset <- apply(mixDataset[geneIntersect, ], 2, as.numeric) -->
<!-- rownames(refDataset) <- rownames(mixDataset) <- geneIntersect -->

<!-- r_dataset <- list('B' = mixDataset, "P_cb" = P_cb, "W_cb" = refDataset) -->

<!-- bestHP <- list("lambda" = 17.80878, "gamma" = 1.686415, p_prime = 0.1483778) -->

<!-- resultDicepro <- DICEPRO::nmf_lbfgsb(r_dataset, p_prime = bestHP$p_prime, lambda_ = bestHP$lambda, gamma_par = bestHP$gamma)  -->

<!-- write.table(cbind("Mixture" = rownames(resultDicepro$H), resultDicepro$H),  -->
<!--             paste0(mixDatasetName, "_", refDatasetName,"/Dicepro.tsv"),  -->
<!--             sep = "\t", row.names = FALSE, quote = FALSE) -->
<!-- ``` -->


<!-- ```{r format predictions} -->
<!-- input_file <- file.path(paste0(mixDatasetName, "_", refDatasetName), "Dicepro.tsv") -->
<!-- output_file <- file.path(paste0(mixDatasetName, "_", refDatasetName), "diceproReformattedPredictions.tsv") -->
<!-- truth_file <- file.path("inst/extdata/truthProportion", paste0("TrueProps", mixDatasetName, ".tsv")) -->

<!-- cmd <- paste( -->
<!--   "python inst/2ReformatPredictions/A_FormatPredictions.py", -->
<!--   input_file, -->
<!--   truth_file, -->
<!--   ">", -->
<!--   output_file -->
<!-- ) -->

<!-- system(cmd) -->
<!-- ``` -->


<!-- ```{r comput metric} -->
<!-- goldProp <- read.delim(truth_file, sep = "\t", header = TRUE, row.names = 1, stringsAsFactors = FALSE) -->
<!-- predProp <- read.delim(output_file, sep = "\t", header = TRUE, row.names = 1, stringsAsFactors = FALSE) -->

<!-- intersectCT <- intersect(colnames(goldProp), colnames(predProp)) -->

<!-- intersectSample <- intersect(rownames(goldProp), rownames(predProp)) -->

<!-- resultPerfrom <- compute_metrics(goldProp[intersectSample, intersectCT], predProp[intersectSample, intersectCT]) -->

<!-- write.csv(resultPerfrom,  -->
<!--           paste0("inst/2ReformatPredictions/metrics_Dicepro_",  -->
<!--                  bulkName , "_", refName, ".csv"),  -->
<!--           row.names = FALSE) -->
<!-- ``` -->


<!-- ```{r save all result to one dataframe} -->
<!-- pathResult <- paste0(mixDatasetName, "_", refDatasetName, "/optim/results") -->
<!-- files_json <- list.files(path = pathResult, pattern = "*.json", full.names = TRUE) -->


<!-- extract_json_info <- function(fichier) { -->
<!--   json_data <- fromJSON(fichier) -->

<!--   returned <- json_data$returned_dict -->
<!--   params <- json_data$current_params -->

<!--   data.frame( -->
<!--     loss = returned$loss, -->
<!--     constraint = returned$constraint, -->
<!--     status = returned$status, -->
<!--     start_time = returned$start_time, -->
<!--     duration = returned$duration, -->
<!--     gamma = params$gamma, -->
<!--     lambda_ = params$lambda_, -->
<!--     p_prime = params$p_prime, -->
<!--     stringsAsFactors = FALSE -->
<!--   ) -->
<!-- } -->

<!-- resultats <- do.call(rbind, lapply(files_json, extract_json_info)) -->

<!-- file_save <- file.path(paste0(mixDatasetName, "_", refDatasetName), "hyperopt_resultats.csv") -->
<!-- write.csv(resultats, file_save, row.names = FALSE) -->

<!-- cat("✅ Résultats sauvegardés dans :", file_save, "\n") -->

<!-- ``` -->


