---
title: "test_simulation"
author: "Kalidou BA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test_simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(DICEPRO)
library(ADAPTS)
library(NMF)
library(MASS)
```



```{r}
simcor <- function (x, ymean=0, ysd=1, correlation=0) {
  n <- length(x)
  y <- rnorm(n)
  z <- correlation * scale(x)[,1] + sqrt(1 - correlation^2) *
    scale(resid(lm(y ~ x)))[,1]
  yresult <- ymean + ysd * z
  as.vector(yresult)
}
```



```{r}
nCellsType <- 22
data(LM22)
corLm22 <- unname(cor(LM22))
sizeVal <- (nCellsType*nCellsType-nCellsType)/2
val <- corLm22[lower.tri(corLm22,diag = FALSE)]
y <- c()
for (m in 1:nCellsType%/%22+1) {
  y <- c(y,simcor(val,mean(val),sd(val),sample(seq(.7,.8,by=.01),1)))
}
y <- y[1:sizeVal]
corr <- matrix(1,ncol = nCellsType,nrow = nCellsType)
corr[lower.tri(corr,diag = FALSE)] <- y
corr <- t(corr)
corr[lower.tri(corr,diag = FALSE)] <- y
V <- cov(corr)
corr <- cov2cor(V)
```



```{r}
nGenes <- 100
nSample <- 20
simulation <- DICEPRO::simulation(loi = "gauss", scenario = " ", bias = TRUE, corr = corr,
                         nSample = nSample, prop = NULL,
                         nGenes = nGenes, nCellsType = nCellsType)

prop <- simulation$prop
reference <- simulation$reference
bulk <- simulation$bulk
```

Let's consider as unknown populations of cells of `10%, 20%, 30%, 40% and 50%`, populations of cells, chosen at random from the reference matrix, as unknown and first analyse the significant impact on the accuracy and reliability of cell deconvolution methods.

```{r}
set.seed(2101)
percs <- 0.3 # seq(0.1, 0.5, 0.1)
cellTypeOut <- list()
for (p in percs) {
  num_samples <- round(ncol(reference) * p)
  sample_indices <- sample(1:ncol(reference), num_samples)
  cellTypeOut[[as.character(num_samples)]] <- sample_indices
}
names(cellTypeOut) <- paste0(as.character(percs * 100), "%")
```



```{r, message=FALSE}
set.seed(2101)
refDataIncomplet <- reference[,-cellTypeOut$`30%`]

result <- DICEPRO(reference = refDataIncomplet, bulk = as.matrix(simulation$bulk), methodDeconv = "DCQ", W_prime = 0, p_prime = 0, gamma_par = 10^12)
result
```

