# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_grad_eigen_fast <- function(W, H, B, sigma, lambda, gamma) {
    .Call(`_DICEPRO_compute_grad_eigen_fast`, W, H, B, sigma, lambda, gamma)
}

compute_obj_term1_eigen_fast <- function(W, H, B, sigma) {
    .Call(`_DICEPRO_compute_obj_term1_eigen_fast`, W, H, B, sigma)
}

