# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_obj_term1_arma <- function(W, H, B, sigma) {
    .Call(`_DICEPRO_compute_obj_term1_arma`, W, H, B, sigma)
}

